name: Add Julia Registry
author: Chris de Graaf
description: Clone a private Julia registry and configure Pkg access
inputs:
  key:
    description: SSH private key contents
    required: true
  registry:
    description: Registry to clone (owner/repo)
    required: true
runs:
  using: node20
  main: main.js
  post: post.js
branding:
  icon: package
  color: red
